package:
  name: awkward-cpp
  version: '34'
  top-level:
  - awkward_cpp

source:
  url: 
    https://files.pythonhosted.org/packages/bd/0d/64ce9e9f6164a1bf8f0c32f86f5e705598093f16158d9b73b3e33c00ec35/awkward-cpp-34.tar.gz
  sha256: 39ac814d769f38ade9a5f6c39b85b07bbc05af56342fb15742edce1237f9e049

build:
  exports: requested

requirements:
  run:
  - numpy

test:
  imports:
  - awkward_cpp

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
extra:
  recipe-maintainers:
  - agoose77
